services:
  # Aplicación Flask (Usuario)
  flask_user:
    build:
      context: ./Flask_User
      dockerfile: Dockerfile
    container_name: oko_vision_flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./Flask_User:/app
    networks:
      - oko_network

  # Aplicación Laravel (Administrador)
  laravel_admin:
    build:
      context: ./Laravel_Admin
      dockerfile: Dockerfile
    container_name: oko_vision_laravel
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./Laravel_Admin:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - oko_network


networks:
  oko_network:
    driver: bridge
